version: '3.8'

services:
  razorpages:
    build:
      context: .
      dockerfile: RazorPages/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my-network
    volumes:
      - ./RazorPages/appsettings.json:/app/appsettings.json
      - ./RazorPages/appsettings.Development.json:/app/appsettings.Development.json

  restapi:
    build:
      context: .
      dockerfile: RestApi/Dockerfile
    ports:
      - "5046:5046"
    networks:
      - my-network
    volumes:
      - ./RestApi/appsettings.json:/app/appsettings.json
      - ./RestApi/appsettings.Development.json:/app/appsettings.Development.json

networks:
  my-network:
    driver: bridge
