version: '3.4'

services:
  razorpages:
    image: ${DOCKER_REGISTRY-}razorpages
    build:
      context: .
      dockerfile: RazorPages/Dockerfile
    networks: 
    - my-network

  restapi:
    image: ${DOCKER_REGISTRY-}restapi
    build:
      context: .
      dockerfile: RestApi/Dockerfile
    networks: 
    - my-network

networks:
  my-network:
