apiVersion: apps/v1
kind: Deployment
metadata:
  name: razorpages-app
spec:
  replicas: 2  # You can scale as needed
  selector:
    matchLabels:
      app: razorpages-app
  template:
    metadata:
      labels:
        app: razorpages-app
    spec:
      containers:
        - name: razorpages-app
          image: razorpages:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080  # Expose port 8080 as defined in Dockerfile
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"  # Adjust if needed for your environment
---
apiVersion: v1
kind: Service
metadata:
  name: razorpages-service
spec:
  selector:
    app: razorpages-app
  ports:
    - port: 80
      targetPort: 8080  # Expose port 8080 externally
  type: NodePort  # Use NodePort for external access (or ClusterIP for internal use)
