apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-app
spec:
  replicas: 2  # Scale as needed
  selector:
    matchLabels:
      app: restapi-app
  template:
    metadata:
      labels:
        app: restapi-app
    spec:
      containers:
        - name: restapi-app
          image: restapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5046  # Expose port 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5046"
---
apiVersion: v1
kind: Service
metadata:
  name: restapi-service
spec:
  selector:
    app: restapi-app
  ports:
    - port: 5046
      targetPort: 5046  # Expose port 8080 externally
  type: NodePort  # Use NodePort for external access (or ClusterIP for internal use)
